### ISSUE TITLE
Not delegating all methods in InputStream may cause problems

### ISSUE THREAD

**Issue by StFS** [GAumala/blog#13]
Hi... it's me again ;)

There is something else to be aware of regarding the ObservableInputStream blog post. If you construct an `ObservableInputStream` wrapping some custom `InputStream` type that has overwritten any of the other methods of InputStream (such as `readAllBytes` or `readNBytes`) those overwritten implementations won't be called. Technically, you need to delegate _all_ `InputStream` methods to ensure this doesn't happen.

Below is an example of what I'm talking about:

```kotlin
class MyCustomInputStream : ByteArrayInputStream {
    constructor(b: ByteArray) : super(b)

    override fun readNBytes(b: ByteArray?, off: Int, len: Int): Int {
        println("I'm reading N bytes in my custom input stream")
        return super.readNBytes(b, off, len)
    }

    override fun readAllBytes(): ByteArray {
        println("I'm reading all bytes in my custom input stream")
        return super.readAllBytes()
    }
}

    // and here's the test
    // note that this will not print out "I'm reading N/all bytes in my custom input stream"
    @Test
    fun testObservableInputStreamReadAllBytesMeasurements() {
        var bytesRead = 0L
        val ois = ObservableInputStream(MyCustomInputStream(bytesWritten)) {
            println("read bytes: $it")
            bytesRead = it
        }
        val bytesReadContent = ois.use { it.readAllBytes() }
        Assertions.assertArrayEquals(bytesReadContent, bytesWritten)
        Assertions.assertEquals(bytesWritten.size, bytesRead.toInt())
    }
```

An example of an `InputStream` subclass that's part of the JDK itself is `ByteArrayInputStream`. That class overwrites `markSupported()` among others. Here's some sample code that demonstrates the problem with that:

```kotlin
        val ba = ByteArray(100)
        Random().nextBytes(ba)
        val bais = ByteArrayInputStream(ba)
        println("before wrapping markSupported(): " + bais.markSupported())  // prints true
        val ois = ObservableInputStream(bais) {
            // noop
        }
        println("after wrapping markSupported(): " + ois.markSupported()) // prints false
```

So to avoid confusion and mysterious bugs in the code of people who might follow your blog examples verbatim, I'd either explicitly override all the methods in `InputStream` and delegate them or add some text explaining this potential gotcha.

**Comment by StFS** [comment]
Sorry @GAumala for being a pain in the ass ;)

But it's not only the `readNBytes()` and `readAllBytes()` that might be problematic. The method `markSupported()` has been in the JDK from the start and your delegator does not delegate that method which can lead to unintended behaviour (see the second example in the issue).

**Comment by GAumala** [comment]
Hey, sorry for the delay. Yeah you are totally right, my bad. I edited the post once more. Thanks again!
